POST  https://8080-isabellymir-provaapimar-xai4i69xpyw.ws-us114.gitpod.io/receitas
Content-Type: application/json

{
    "nome": "Bolo de Chocolate",
    "instrucoes": "Misture todos os ingredientes e asse por 30 minutos.",
    "categoria": {"id": 1},
    "ingrediente": {"id": 1}
}